//
// Created by huangcanjia <huangcanjia0214@gmail.com> on 2026/9/17.
// Copyright (c) 2026 Graphics@XMU (https://graphics.xmu.edu.cn). All rights reserved.
//
#include "axis_aligned_simplex_clipper.h"
#include <cassert>
#include <cmath>
#include <geogram/numerics/predicates.h>
#include "log.h"

namespace
{
    /* Exactness helpers.
     *
     * The clipper both *decides* (which side of a cut plane a vertex is on) and
     * *constructs* (it interpolates the intersection of a simplex with a cut plane in
     * double precision). The two are not equally accurate:
     *
     *  - deciding is exact: a cut plane is axis aligned, so comparing one coordinate with
     *    the plane value compares two doubles, which is exact (`side_of_aligned_plane()`);
     *  - constructing is not: a generated vertex is only the correctly rounded
     *    interpolation, so it lies at a distance of a few ulps from the ideal
     *    intersection, and the sign of the tiny determinant of the resulting sliver cells
     *    is not decided by the stored coordinates at all.
     *
     * Hence the two guarantees that the clipper builds on top of them:
     *  - generated vertices are snapped exactly onto the cut plane they were generated
     *    for, so that every cell sharing such a vertex stores bit identical coordinates;
     *  - the (`few`) decisions that are taken on generated vertices use an exact
     *    predicate, which answers for the *stored* doubles (never for higher precision
     *    intermediates that the caller cannot see).
     */

    /**
     * Side of the coordinate `c` relative to the axis aligned plane `x == t`.
     * @retval GEO::POSITIVE if `c` is strictly above the plane.
     * @retval GEO::ZERO if `c` is exactly on the plane.
     * @retval GEO::NEGATIVE if `c` is strictly below the plane.
     * @note Exact, and predicate free: comparing two doubles is exact, so no vertex is
     *  ever classified on the wrong side, however close to the plane it is. This is what
     *  allows the axis aligned clipper to classify exactly while only interpolating
     *  intersections in double precision.
     */
    [[nodiscard]] inline GEO::Sign side_of_aligned_plane(const double c, const double t) {
        return GEO::geo_cmp(c, t);
    }

    /**
     * Interpolates a point of the segment `[u, v]` onto the axis aligned plane
     * `x[dim] == t`, `r` being the interpolation ratio (`0` gives `u`, `1` gives `v`).
     * @note The result is snapped exactly onto the cut plane, i.e. `p[dim] == t` holds
     *  exactly, so that all the cells sharing the generated vertex store bit identical
     *  coordinates.
     * @note A coordinate on which `u` and `v` agree exactly is copied rather than
     *  interpolated: every point of `[u, v]` has that coordinate, and interpolating it in
     *  double precision drifts by an ulp. This is what would otherwise take a vertex of a
     *  face generated by an anterior cut plane out of that plane, and open a crack between
     *  the cells sharing the face.
     */
    template <GEO::index_t DIM>
    [[nodiscard]] inline GEO::vecng<DIM, double> interpolate_on_aligned_plane(
        const GEO::vecng<DIM, double>& u, const GEO::vecng<DIM, double>& v,
        const double r, const GEO::index_t dim, const double t
        ) {
        GEO::vecng<DIM, double> p;
        for (GEO::index_t i = 0; i < DIM; ++i)
            p[i] = (u[i] == v[i]) ? u[i] : (1-r)*u[i] + r*v[i];
        p[dim] = t;
        return p;
    }

    /** Machine epsilon (2^-53); the error bounds below are derived from it. */
    constexpr double DOUBLE_EPSILON = 1.1102230246251565e-16;

    /**
     * Size (longest edge) of the cells `[0, nb)`, from which the orientation checks below derive
     * their bound; returns `0` when the checks are not compiled in.
     */
    template <GEO::index_t DIM, GEO::index_t N>
    [[nodiscard]] inline double debug_cell_scale(
        [[maybe_unused]] const std::vector<GEO::vecng<DIM, double>>& coords,
        [[maybe_unused]] const GEO::index_t nb
        ) {
#ifndef NDEBUG
        double scale = 0.0;
        for (GEO::index_t c = 0; c < nb; ++c)
            for (GEO::index_t i = 0; i < N; ++i)
                for (GEO::index_t j = i+1; j < N; ++j)
                    scale = std::max(scale, GEO::length(coords[N*c+i]-coords[N*c+j]));
        return scale;
#else
        return 0.0;
#endif
    }

    /**
     * Bound below which the orientation of a generated cell cannot be told from its stored
     * coordinates, `scale` being the size of the cell it was cut from.
     * @details The predicate itself is exact (`GEO::PCK::orient_3d()` answers for the stored
     *  doubles), so this is not the filtering bound of the predicate but the error of the
     *  *construction*: a generated vertex is the correctly rounded interpolation of an
     *  intersection, so it lies about one ulp of the coordinates it comes from, i.e.
     *  `DOUBLE_EPSILON * scale`, away from its ideal position. An orientation below
     *  `DOUBLE_EPSILON * scale^3` is therefore decided by that rounding rather than by the
     *  geometry, and a cell thinner than that may legitimately come out inverted (storing
     *  intersections as doubles cannot do better: this needs exact constructions, not exact
     *  predicates). Measured on 100k random cases, every cell inverted by that rounding has an
     *  orientation below `1.3 * DOUBLE_EPSILON * scale^3`, while a wrong corner list inverts a
     *  whole cell and is above it by about fifteen orders of magnitude.
     * @note Sizing the bound with the cell's own size, or with the determinant's permanent
     *  (Shewchuk's filter), would not do: a cell generated by a cut through a vertex has a
     *  collapsed edge, so both shrink with the cell instead of with the rounding error.
     */
    constexpr double ORIENTATION_SAFETY_FACTOR = 64.0;

    [[nodiscard]] inline double orientation_error_bound(const double scale) {
        return ORIENTATION_SAFETY_FACTOR * DOUBLE_EPSILON * scale*scale*scale;
    }

    /**
     * Checks that none of the generated triangles `[from, to)` is inverted.
     * @note Debug builds only: does nothing when `NDEBUG` is defined.
     * @note The orientation is decided by an exact predicate, evaluated on the stored
     *  coordinates. A triangle thinner than the rounding error of the interpolation that
     *  generated it may legitimately be inverted: storing intersections as doubles cannot
     *  do better, and fixing it would need exact constructions rather than exact
     *  predicates. Such triangles are therefore recognized by their determinant falling
     *  below its error bound, and are not reported.
     * @note Only checked for `DIM == 2`, where the orientation of a triangle is a scalar
     *  (its signed area). In 3d a triangle has an area *vector* rather than a signed
     *  area, and the area vector of a generated triangle is only defined up to the same
     *  rounding error; what keeps the generated triangles consistently oriented in 3d is
     *  that every emitted corner list is a cyclic rotation of its parent's.
     */
    template <GEO::index_t DIM>
    inline void debug_check_tri_orientations(
        [[maybe_unused]] const std::vector<GEO::vecng<DIM, double>>& coords,
        [[maybe_unused]] const GEO::index_t from,
        [[maybe_unused]] const GEO::index_t to,
        [[maybe_unused]] const double cell_scale
        ) {
#ifndef NDEBUG
        if constexpr (DIM == 2) {
            for (GEO::index_t f = from; f < to; ++f) {
                const auto& p0 = coords[3*f];
                const auto& p1 = coords[3*f+1];
                const auto& p2 = coords[3*f+2];
                const auto u = p1-p0;
                const auto v = p2-p0;
                assert(GEO::PCK::orient_2d(p0, p1, p2) != GEO::NEGATIVE ||
                       std::abs(u[0]*v[1]-u[1]*v[0]) <= orientation_error_bound(cell_scale));
            }
        }
#endif
    }

    /**
     * Checks that none of the generated tetrahedra `[from, to)` is inverted.
     * @note Debug builds only: does nothing when `NDEBUG` is defined.
     * @note A tetrahedron is degenerate (zero volume) when the cut plane goes through one
     *  of its vertices: that is expected, degenerate cells are kept on purpose, and a
     *  zero orientation satisfies this check.
     * @see debug_check_tri_orientations() for the error bound and the sliver cells.
     */
    inline void debug_check_tet_orientations(
        [[maybe_unused]] const std::vector<GEO::vec3>& coords,
        [[maybe_unused]] const GEO::index_t from,
        [[maybe_unused]] const GEO::index_t to,
        [[maybe_unused]] const double cell_scale
        ) {
#ifndef NDEBUG
        for (GEO::index_t c = from; c < to; ++c) {
            const auto& p0 = coords[4*c];
            const auto& p1 = coords[4*c+1];
            const auto& p2 = coords[4*c+2];
            const auto& p3 = coords[4*c+3];
            const auto u = p1-p0;
            const auto v = p2-p0;
            const auto w = p3-p0;
            assert(GEO::PCK::orient_3d(p0, p1, p2, p3) != GEO::NEGATIVE ||
                   std::abs(GEO::dot(u, GEO::cross(v, w))) <= orientation_error_bound(cell_scale));
        }
#endif
    }
}

namespace geolio
{
    template <GEO::index_t DIM>
    AxisAlignedTriClipper<DIM>::AxisAlignedTriClipper(
        const GEO::vecng<DIM, double>& p0,
        const GEO::vecng<DIM, double>& p1,
        const GEO::vecng<DIM, double>& p2
        ) {
        this->partitions_.push_back(0);

        this->coords_.reserve(3);
        this->coords_.push_back(p0);
        this->coords_.push_back(p1);
        this->coords_.push_back(p2);

        this->bary_coords_.reserve(3);
        this->bary_coords_.emplace_back(1, 0, 0);
        this->bary_coords_.emplace_back(0, 1, 0);
        this->bary_coords_.emplace_back(0, 0, 1);

        this->facet_cut_plane_.reserve(3);
        this->facet_cut_plane_.push_back(GEO::NO_INDEX);
        this->facet_cut_plane_.push_back(GEO::NO_INDEX);
        this->facet_cut_plane_.push_back(GEO::NO_INDEX);
    }

    template <GEO::index_t DIM>
    void AxisAlignedTriClipper<DIM>::clip(
        const GEO::index_t dim,
        const double t
        ) {
        assert(dim < DIM);
        assert(this->coords_.size()%3 == 0);
        assert(this->bary_coords_.size()%3 == 0);

        const GEO::index_t PREV_TRIS_NB = this->partitions_.size();
        /* Debug builds: the size of the cells of this call, from which the orientation checks at
           the end of this function derive their bound (see orientation_error_bound()). */
        [[maybe_unused]] const double CELL_SCALE = debug_cell_scale<DIM, 3>(this->coords_, PREV_TRIS_NB);
        assert(this->coords_.size()/3 == PREV_TRIS_NB);
        assert(this->bary_coords_.size()/3 == PREV_TRIS_NB);

        /* Cut each triangle */
        std::array<double, 3> dists{}; /* coordinate minus plane value, used for the ratios */
        std::array<GEO::Sign, 3> sides{}; /* exact side of each vertex, see side_of_aligned_plane() */
        for (GEO::index_t f = 0; f < PREV_TRIS_NB; ++f) {
            const auto origin_partition = this->partitions_[f];

            dists[0] = this->coords_[3*f][dim]-t;
            dists[1] = this->coords_[3*f+1][dim]-t;
            dists[2] = this->coords_[3*f+2][dim]-t;
            sides[0] = side_of_aligned_plane(this->coords_[3*f][dim], t);
            sides[1] = side_of_aligned_plane(this->coords_[3*f+1][dim], t);
            sides[2] = side_of_aligned_plane(this->coords_[3*f+2][dim], t);

            /* A vertex lying exactly on the cut plane counts as being on the *negative*
               side (closed negative half space), so a triangle is reported as being on the
               positive side only when it is strictly on it. */
            const auto positive_nb = static_cast<GEO::index_t>(
                (sides[0] == GEO::POSITIVE) + (sides[1] == GEO::POSITIVE) + (sides[2] == GEO::POSITIVE)
                );

            if (positive_nb == 0)
                continue;
            else if (positive_nb == 3)
                this->partitions_[f] |= (1<<this->cut_planes_nb_);
            else if (positive_nb == 1) {
                for (GEO::index_t lv = 0; lv < 3; ++lv) {
                    if (sides[lv] != GEO::POSITIVE)
                        continue;

                    const GEO::index_t lv0 = lv;
                    const GEO::index_t lv1 = (lv+1)%3;
                    const GEO::index_t lv2 = (lv+2)%3;

                    const double r01 = std::abs(dists[lv0]) /  (std::abs(dists[lv0])+std::abs(dists[lv1]));
                    const double r02 = std::abs(dists[lv0]) /  (std::abs(dists[lv0])+std::abs(dists[lv2]));
                    assert(r01 >= 0 && r01 <=1);
                    assert(r02 >= 0 && r02 <=1);
                    /* `lv1` and `lv2` are not strictly positive, so they may lie exactly on
                       the cut plane: the ratio is then exactly 1 and the generated vertex
                       coincides exactly with `p1`/`p2`. This is what makes the degenerate
                       triangles that such a cut produces *exactly* degenerate rather than
                       almost degenerate (they are kept on purpose, see the class doc). */
                    assert(dists[lv1] != 0 || r01 == 1);
                    assert(dists[lv2] != 0 || r02 == 1);

                    const auto p0 = this->coords_[3*f+lv0];
                    const auto p1 = this->coords_[3*f+lv1];
                    const auto p2 = this->coords_[3*f+lv2];
                    const auto p01 = interpolate_on_aligned_plane(p0, p1, r01, dim, t);
                    const auto p02 = interpolate_on_aligned_plane(p0, p2, r02, dim, t);

                    const auto bp0 = this->bary_coords_[3*f+lv0];
                    const auto bp1 = this->bary_coords_[3*f+lv1];
                    const auto bp2 = this->bary_coords_[3*f+lv2];
                    const auto bp01 = (1-r01)*bp0 + r01*bp1;
                    const auto bp02 = (1-r02)*bp0 + r02*bp2;

                    this->partitions_.reserve(this->partitions_.size()+2);
                    this->coords_.reserve(this->coords_.size()+6);
                    this->bary_coords_.reserve(this->bary_coords_.size()+6);
                    this->facet_cut_plane_.reserve(this->facet_cut_plane_.size()+6);

                    this->partitions_.push_back(origin_partition);
                    this->coords_.push_back(p1);    this->bary_coords_.push_back(bp1);
                    this->coords_.push_back(p02);   this->bary_coords_.push_back(bp02);
                    this->coords_.push_back(p01);   this->bary_coords_.push_back(bp01);
                    /* For a triangle, `facet_cut_plane_[3*f+i]` describes the edge
                       `(i, (i+1)%3)` (and not the facet opposite the ith vertex, as for a
                       tetrahedron, see the class documentation): the cut plane lies on the edge
                       bounded by the generated corners, and the two other entries inherit the
                       border edges the generated corners lie on. */
                    this->facet_cut_plane_.push_back(GEO::NO_INDEX);
                    this->facet_cut_plane_.push_back(this->cut_planes_nb_);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv0]);

                    this->partitions_.push_back(origin_partition);
                    this->coords_.push_back(p1);    this->bary_coords_.push_back(bp1);
                    this->coords_.push_back(p2);    this->bary_coords_.push_back(bp2);
                    this->coords_.push_back(p02);   this->bary_coords_.push_back(bp02);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv1]);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv2]);
                    this->facet_cut_plane_.push_back(GEO::NO_INDEX);

                    this->partitions_[f] |= (1<<this->cut_planes_nb_);
                    this->coords_[3*f+lv1] = p01;   this->bary_coords_[3*f+lv1] = bp01;
                    this->coords_[3*f+lv2] = p02;   this->bary_coords_[3*f+lv2] = bp02;
                    this->facet_cut_plane_[3*f+lv1] = this->cut_planes_nb_;

                    break;
                }
            }
            else {
                assert(positive_nb == 2);

                for (GEO::index_t lv = 0; lv < 3; ++lv) {
                    if (sides[lv] == GEO::POSITIVE)
                        continue;

                    const GEO::index_t lv0 = lv;
                    const GEO::index_t lv1 = (lv+1)%3;
                    const GEO::index_t lv2 = (lv+2)%3;

                    const double r01 = std::abs(dists[lv0]) /  (std::abs(dists[lv0])+std::abs(dists[lv1]));
                    const double r02 = std::abs(dists[lv0]) /  (std::abs(dists[lv0])+std::abs(dists[lv2]));
                    assert(r01 >= 0 && r01 <=1);
                    assert(r02 >= 0 && r02 <=1);
                    /* `lv0` is not strictly positive, so it may lie exactly on the cut plane:
                       the ratios are then exactly 0 and the generated vertices coincide exactly
                       with `p0`. This is what makes the degenerate triangles that such a cut
                       produces *exactly* degenerate rather than almost degenerate (they are
                       kept on purpose, see the class doc). */
                    assert(dists[lv0] != 0 || (r01 == 0 && r02 == 0));

                    const auto p0 = this->coords_[3*f+lv0];
                    const auto p1 = this->coords_[3*f+lv1];
                    const auto p2 = this->coords_[3*f+lv2];
                    const auto p01 = interpolate_on_aligned_plane(p0, p1, r01, dim, t);
                    const auto p02 = interpolate_on_aligned_plane(p0, p2, r02, dim, t);

                    const auto bp0 = this->bary_coords_[3*f+lv0];
                    const auto bp1 = this->bary_coords_[3*f+lv1];
                    const auto bp2 = this->bary_coords_[3*f+lv2];
                    const auto bp01 = (1-r01)*bp0 + r01*bp1;
                    const auto bp02 = (1-r02)*bp0 + r02*bp2;

                    this->partitions_.reserve(this->partitions_.size()+2);
                    this->coords_.reserve(this->coords_.size()+6);
                    this->bary_coords_.reserve(this->bary_coords_.size()+6);
                    this->facet_cut_plane_.reserve(this->facet_cut_plane_.size()+6);

                    this->partitions_.push_back(origin_partition | (1<<this->cut_planes_nb_));
                    this->coords_.push_back(p1);    this->bary_coords_.push_back(bp1);
                    this->coords_.push_back(p02);   this->bary_coords_.push_back(bp02);
                    this->coords_.push_back(p01);   this->bary_coords_.push_back(bp01);
                    /* For a triangle, `facet_cut_plane_[3*f+i]` describes the edge
                       `(i, (i+1)%3)` (and not the facet opposite the ith vertex, as for a
                       tetrahedron, see the class documentation): the cut plane lies on the edge
                       bounded by the generated corners, and the two other entries inherit the
                       border edges the generated corners lie on. */
                    this->facet_cut_plane_.push_back(GEO::NO_INDEX);
                    this->facet_cut_plane_.push_back(this->cut_planes_nb_);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv0]);

                    this->partitions_.push_back(origin_partition | (1<<this->cut_planes_nb_));
                    this->coords_.push_back(p1);    this->bary_coords_.push_back(bp1);
                    this->coords_.push_back(p2);    this->bary_coords_.push_back(bp2);
                    this->coords_.push_back(p02);   this->bary_coords_.push_back(bp02);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv1]);
                    this->facet_cut_plane_.push_back(this->facet_cut_plane_[3*f+lv2]);
                    this->facet_cut_plane_.push_back(GEO::NO_INDEX);

                    // this->partitions_[f] = origin_partition;
                    this->coords_[3*f+lv1] = p01;   this->bary_coords_[3*f+lv1] = bp01;
                    this->coords_[3*f+lv2] = p02;   this->bary_coords_[3*f+lv2] = bp02;
                    this->facet_cut_plane_[3*f+lv1] = this->cut_planes_nb_;

                    break;
                }
            }
        }

        /* Debug builds: check, with an exact predicate, that no triangle generated by this
           call is inverted. The triangles `[0, PREV_TRIS_NB)` were modified in place by the
           loop above, so the whole buffer has to be checked. */
        debug_check_tri_orientations(
            this->coords_, 0, static_cast<GEO::index_t>(this->coords_.size())/3, CELL_SCALE
            );

        ++this->cut_planes_nb_;
        if (this->cut_planes_nb_ > 32)
            LOG::WARN("Cut planes nb == {} > 32, partitions out of uint32_t!", this->cut_planes_nb_);
    }

    template class AxisAlignedTriClipper<2>;
    template class AxisAlignedTriClipper<3>;

    AxisAlignedTetClipper::AxisAlignedTetClipper(
        const GEO::vec3& p0,
        const GEO::vec3& p1,
        const GEO::vec3& p2,
        const GEO::vec3& p3
        ) {
        partitions_.push_back(0);

        coords_.reserve(4);
        coords_.push_back(p0);
        coords_.push_back(p1);
        coords_.push_back(p2);
        coords_.push_back(p3);

        bary_coords_.reserve(4);
        bary_coords_.emplace_back(1, 0, 0, 0);
        bary_coords_.emplace_back(0, 1, 0, 0);
        bary_coords_.emplace_back(0, 0, 1, 0);
        bary_coords_.emplace_back(0, 0, 0, 1);

        facet_cut_plane_.reserve(4);
        facet_cut_plane_.push_back(GEO::NO_INDEX);
        facet_cut_plane_.push_back(GEO::NO_INDEX);
        facet_cut_plane_.push_back(GEO::NO_INDEX);
        facet_cut_plane_.push_back(GEO::NO_INDEX);
    }

    void AxisAlignedTetClipper::clip(
        const GEO::index_t dim,
        const double t
        ) {
        assert(dim < 3);
        assert(coords_.size()%4 == 0);
        assert(bary_coords_.size()%4 == 0);

        const GEO::index_t PREV_TETS_NB = partitions_.size();
        /* @see AxisAlignedTriClipper::clip() for `CELL_SCALE`. */
        [[maybe_unused]] const double CELL_SCALE = debug_cell_scale<3, 4>(coords_, PREV_TETS_NB);
        assert(coords_.size()/4 == PREV_TETS_NB);
        assert(bary_coords_.size()/4 == PREV_TETS_NB);

        /* Cut each tetrahedron */
        std::array<double, 4> dists{}; /* coordinate minus plane value, used for the ratios */
        std::array<GEO::Sign, 4> sides{}; /* exact side of each vertex, see side_of_aligned_plane() */
        for (GEO::index_t c = 0; c < PREV_TETS_NB; ++c) {
            const auto origin_partition = partitions_[c];

            dists[0] = coords_[4*c][dim]-t;
            dists[1] = coords_[4*c+1][dim]-t;
            dists[2] = coords_[4*c+2][dim]-t;
            dists[3] = coords_[4*c+3][dim]-t;
            sides[0] = side_of_aligned_plane(coords_[4*c][dim], t);
            sides[1] = side_of_aligned_plane(coords_[4*c+1][dim], t);
            sides[2] = side_of_aligned_plane(coords_[4*c+2][dim], t);
            sides[3] = side_of_aligned_plane(coords_[4*c+3][dim], t);

            /* A vertex lying exactly on the cut plane counts as being on the *negative*
               side (closed negative half space), so a tetrahedron is reported as being on
               the positive side only when it is strictly on it.
               @note The vertices lying exactly on the plane are nevertheless counted
               separately: they are what makes the 2/2 configuration degenerate, and such a
               configuration is not decomposed by the 2/2 branch below (see the comments of
               the branches). */
            const auto positive_nb = static_cast<GEO::index_t>(
                (sides[0] == GEO::POSITIVE) + (sides[1] == GEO::POSITIVE) +
                (sides[2] == GEO::POSITIVE) + (sides[3] == GEO::POSITIVE)
                );
            const auto zero_nb = static_cast<GEO::index_t>(
                (sides[0] == GEO::ZERO) + (sides[1] == GEO::ZERO) +
                (sides[2] == GEO::ZERO) + (sides[3] == GEO::ZERO)
                );

            if (positive_nb == 0)
                continue;
            if (positive_nb == 4)
                partitions_[c] |= (1<<cut_planes_nb_);
            else if (positive_nb == 1) {
                for (GEO::index_t lv = 0; lv < 4; ++lv) {
                    if (sides[lv] != GEO::POSITIVE)
                        continue;

                    const GEO::index_t lv0 = lv;
                    const GEO::index_t lv1 = (lv+1)%4;
                    GEO::index_t lv2 = (lv+2)%4;
                    GEO::index_t lv3 = (lv+3)%4;
                    if (lv0%2 == 1)
                        std::swap(lv2, lv3);

                    const double r01 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv1]));
                    const double r02 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv2]));
                    const double r03 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv3]));
                    assert(r01 >= 0 && r01 <= 1);
                    assert(r02 >= 0 && r02 <= 1);
                    assert(r03 >= 0 && r03 <= 1);
                    /* `lv1`, `lv2` and `lv3` are not strictly positive, so they may lie
                       exactly on the cut plane: the ratio is then exactly 1 and the
                       generated vertex coincides exactly with the vertex it interpolates.
                       This is what makes the degenerate tetrahedra that such a cut produces
                       *exactly* degenerate rather than almost degenerate (they are kept on
                       purpose, see the class doc). */
                    assert(dists[lv1] != 0 || r01 == 1);
                    assert(dists[lv2] != 0 || r02 == 1);
                    assert(dists[lv3] != 0 || r03 == 1);

                    const auto p0 = coords_[4*c+lv0];
                    const auto p1 = coords_[4*c+lv1];
                    const auto p2 = coords_[4*c+lv2];
                    const auto p3 = coords_[4*c+lv3];
                    const auto p01 = interpolate_on_aligned_plane(p0, p1, r01, dim, t);
                    const auto p02 = interpolate_on_aligned_plane(p0, p2, r02, dim, t);
                    const auto p03 = interpolate_on_aligned_plane(p0, p3, r03, dim, t);

                    const auto bp0 = bary_coords_[4*c+lv0];
                    const auto bp1 = bary_coords_[4*c+lv1];
                    const auto bp2 = bary_coords_[4*c+lv2];
                    const auto bp3 = bary_coords_[4*c+lv3];
                    const auto bp01 = (1-r01)*bp0 + r01*bp1;
                    const auto bp02 = (1-r02)*bp0 + r02*bp2;
                    const auto bp03 = (1-r03)*bp0 + r03*bp3;

                    partitions_.reserve(partitions_.size()+3);
                    coords_.reserve(coords_.size()+12);
                    bary_coords_.reserve(bary_coords_.size()+12);
                    facet_cut_plane_.reserve(facet_cut_plane_.size()+12);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    facet_cut_plane_.push_back(cut_planes_nb_);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    partitions_[c] |= (1<<cut_planes_nb_);
                    coords_[4*c+lv1] = p01;   bary_coords_[4*c+lv1] = bp01;
                    coords_[4*c+lv2] = p02;   bary_coords_[4*c+lv2] = bp02;
                    coords_[4*c+lv3] = p03;   bary_coords_[4*c+lv3] = bp03;
                    facet_cut_plane_[4*c+lv0] = cut_planes_nb_;

                    break;
                }
            }
            else if (positive_nb == 3 || (positive_nb == 2 && zero_nb == 1)) {
                /* One vertex is not strictly positive (it is the strictly negative one when
                   `positive_nb == 3`, or the strictly negative one of a 2/2 configuration
                   when `positive_nb == 2`) and the three others are on or above the plane.
                   @note The `positive_nb == 2 && zero_nb == 1` case is a 2/2 configuration
                   whose section degenerates: the plane goes through the vertex that lies on
                   it, so the section is a triangle rather than a quadrilateral and the 2/2
                   decomposition does not apply (it would emit inverted cells, since its
                   orientation test is then exactly zero). The configuration is the one
                   handled here, with the vertex lying on the plane playing the role of a
                   positive one: the interpolations that collapse on it have a ratio of
                   exactly 1, and the cells they generate are exactly degenerate. */
                for (GEO::index_t lv = 0; lv < 4; ++lv) {
                    if (sides[lv] == GEO::POSITIVE || (positive_nb == 2 && sides[lv] == GEO::ZERO))
                        continue;

                    const GEO::index_t lv0 = lv;
                    const GEO::index_t lv1 = (lv+1)%4;
                    GEO::index_t lv2 = (lv+2)%4;
                    GEO::index_t lv3 = (lv+3)%4;
                    if (lv0%2 == 1)
                        std::swap(lv2, lv3);

                    const double r01 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv1]));
                    const double r02 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv2]));
                    const double r03 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv3]));
                    assert(r01 >= 0 && r01 <= 1);
                    assert(r02 >= 0 && r02 <= 1);
                    assert(r03 >= 0 && r03 <= 1);
                    /* `lv1`, `lv2` and `lv3` are not strictly positive, so they may lie
                       exactly on the cut plane: the ratio is then exactly 1 and the
                       generated vertex coincides exactly with the vertex it interpolates.
                       This is what makes the degenerate tetrahedra that such a cut produces
                       *exactly* degenerate rather than almost degenerate (they are kept on
                       purpose, see the class doc). */
                    assert(dists[lv1] != 0 || r01 == 1);
                    assert(dists[lv2] != 0 || r02 == 1);
                    assert(dists[lv3] != 0 || r03 == 1);

                    const auto p0 = coords_[4*c+lv0];
                    const auto p1 = coords_[4*c+lv1];
                    const auto p2 = coords_[4*c+lv2];
                    const auto p3 = coords_[4*c+lv3];
                    const auto p01 = interpolate_on_aligned_plane(p0, p1, r01, dim, t);
                    const auto p02 = interpolate_on_aligned_plane(p0, p2, r02, dim, t);
                    const auto p03 = interpolate_on_aligned_plane(p0, p3, r03, dim, t);

                    const auto bp0 = bary_coords_[4*c+lv0];
                    const auto bp1 = bary_coords_[4*c+lv1];
                    const auto bp2 = bary_coords_[4*c+lv2];
                    const auto bp3 = bary_coords_[4*c+lv3];
                    const auto bp01 = (1-r01)*bp0 + r01*bp1;
                    const auto bp02 = (1-r02)*bp0 + r02*bp2;
                    const auto bp03 = (1-r03)*bp0 + r03*bp3;

                    partitions_.reserve(partitions_.size()+3);
                    coords_.reserve(coords_.size()+12);
                    bary_coords_.reserve(bary_coords_.size()+12);
                    facet_cut_plane_.reserve(facet_cut_plane_.size()+12);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p01);   bary_coords_.push_back(bp01);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    facet_cut_plane_.push_back(cut_planes_nb_);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    // partitions_[c] = origin_partition;
                    coords_[4*c+lv1] = p01;   bary_coords_[4*c+lv1] = bp01;
                    coords_[4*c+lv2] = p02;   bary_coords_[4*c+lv2] = bp02;
                    coords_[4*c+lv3] = p03;   bary_coords_[4*c+lv3] = bp03;
                    facet_cut_plane_[4*c+lv0] = cut_planes_nb_;

                    break;
                }
            }
            else if (positive_nb == 2 && zero_nb == 2) {
                /* The plane contains the edge joining the two vertices that are not strictly
                   positive: the tetrahedron is then entirely on the closed positive side, and
                   its negative side has a zero measure, so there is nothing to decompose. */
                partitions_[c] |= (1<<cut_planes_nb_);
            }
            else {
                assert(positive_nb == 2);
                assert(zero_nb == 0);
                GEO::index_t lv0 = GEO::NO_INDEX; // positive
                GEO::index_t lv1 = GEO::NO_INDEX; // positive
                GEO::index_t lv2 = GEO::NO_INDEX; // negative
                GEO::index_t lv3 = GEO::NO_INDEX; // negative
                for (GEO::index_t lv = 0; lv < 4; ++lv) {
                    if (sides[lv] == GEO::POSITIVE) {
                        if (lv0 == GEO::NO_INDEX)
                            lv0 = lv;
                        else
                            lv1 = lv;
                    }
                    else {
                        if (lv2 == GEO::NO_INDEX)
                            lv2 = lv;
                        else
                            lv3 = lv;
                    }
                }
                assert(lv0 != GEO::NO_INDEX); assert(lv1 != GEO::NO_INDEX); assert(lv2 != GEO::NO_INDEX); assert(lv3 != GEO::NO_INDEX);

                const double r02 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv2]));
                const double r03 = std::abs(dists[lv0]) / (std::abs(dists[lv0])+std::abs(dists[lv3]));
                const double r12 = std::abs(dists[lv1]) / (std::abs(dists[lv1])+std::abs(dists[lv2]));
                const double r13 = std::abs(dists[lv1]) / (std::abs(dists[lv1])+std::abs(dists[lv3]));
                assert(r02 >= 0 && r02 <= 1);
                assert(r03 >= 0 && r03 <= 1);
                assert(r12 >= 0 && r12 <= 1);
                assert(r13 >= 0 && r13 <= 1);
                /* `lv2` and `lv3` are not strictly positive, so they may lie exactly on the
                   cut plane: the ratios are then exactly 0 or 1 and the generated vertices
                   coincide exactly with the vertices they interpolate, which is what makes
                   the degenerate tetrahedra that such a cut produces *exactly* degenerate
                   rather than almost degenerate (they are kept on purpose, see the class
                   doc). */
                assert(dists[lv2] != 0 || (r02 == 1 && r12 == 1));
                assert(dists[lv3] != 0 || (r03 == 1 && r13 == 1));

                const auto p0 = coords_[4*c+lv0];
                const auto p1 = coords_[4*c+lv1];
                const auto p2 = coords_[4*c+lv2];
                const auto p3 = coords_[4*c+lv3];
                const auto p02 = interpolate_on_aligned_plane(p0, p2, r02, dim, t);
                const auto p03 = interpolate_on_aligned_plane(p0, p3, r03, dim, t);
                const auto p12 = interpolate_on_aligned_plane(p1, p2, r12, dim, t);
                const auto p13 = interpolate_on_aligned_plane(p1, p3, r13, dim, t);

                const auto bp0 = bary_coords_[4*c+lv0];
                const auto bp1 = bary_coords_[4*c+lv1];
                const auto bp2 = bary_coords_[4*c+lv2];
                const auto bp3 = bary_coords_[4*c+lv3];
                const auto bp02 = (1-r02)*bp0 + r02*bp2;
                const auto bp03 = (1-r03)*bp0 + r03*bp3;
                const auto bp12 = (1-r12)*bp1 + r12*bp2;
                const auto bp13 = (1-r13)*bp1 + r13*bp3;

                partitions_.reserve(partitions_.size()+5);
                coords_.reserve(coords_.size()+20);
                bary_coords_.reserve(bary_coords_.size()+20);
                facet_cut_plane_.reserve(facet_cut_plane_.size()+20);
                /* Decides which of the two mirror decompositions of the section tiles the
                   tetrahedron. This is a *combinatorial* property of the vertex selection: the
                   corner lists below are written for a positively oriented reference, and
                   `(lv0, lv1, lv2, lv3)` is positively oriented exactly when it is an even
                   permutation of the stored vertices, so the parity of that permutation says
                   which mirror applies, exactly.
                   @note Testing it geometrically instead, e.g. with the sign of
                   `orient_3d(p02, p03, p12, p0)` or of `tetra_signed_volume(p02, p03, p12, p0)`
                   (which is the volume of the first cell of the decomposition), agrees with
                   the parity for well separated vertices but decorrelates as soon as the
                   section is thin, i.e. exactly when the cut plane grazes a vertex: the stored
                   section points then have a chirality of their own and the mirrored
                   decomposition is emitted, with inverted cells and a negated partition
                   volume. The parity cannot decorrelate. */
                const GEO::index_t LV[4] = {lv0, lv1, lv2, lv3};
                GEO::index_t inversions_nb = 0;
                for (GEO::index_t i = 0; i < 4; ++i)
                    for (GEO::index_t j = i+1; j < 4; ++j)
                        if (LV[i] > LV[j])
                            ++inversions_nb;

                if (inversions_nb%2 == 1) {
                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p0);    bary_coords_.push_back(bp0);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p0);    bary_coords_.push_back(bp0);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    // partitions_[c] = origin_partition;
                    coords_[4*c+lv0] = p03;   bary_coords_[4*c+lv0] = bp03;
                    coords_[4*c+lv1] = p12;   bary_coords_[4*c+lv1] = bp12;
                    facet_cut_plane_[4*c+lv2] = GEO::NO_INDEX;
                    facet_cut_plane_[4*c+lv3] = GEO::NO_INDEX;
                }
                else {
                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p0);    bary_coords_.push_back(bp0);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition | (1<<cut_planes_nb_));
                    coords_.push_back(p0);    bary_coords_.push_back(bp0);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p1);    bary_coords_.push_back(bp1);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p12);   bary_coords_.push_back(bp12);
                    coords_.push_back(p2);    bary_coords_.push_back(bp2);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv0]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv3]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    partitions_.push_back(origin_partition);
                    coords_.push_back(p13);   bary_coords_.push_back(bp13);
                    coords_.push_back(p02);   bary_coords_.push_back(bp02);
                    coords_.push_back(p03);   bary_coords_.push_back(bp03);
                    coords_.push_back(p3);    bary_coords_.push_back(bp3);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv1]);
                    facet_cut_plane_.push_back(facet_cut_plane_[4*c+lv2]);
                    facet_cut_plane_.push_back(GEO::NO_INDEX);
                    facet_cut_plane_.push_back(cut_planes_nb_);

                    // partitions_[c] = origin_partition;
                    coords_[4*c+lv0] = p02;   bary_coords_[4*c+lv0] = bp02;
                    coords_[4*c+lv1] = p13;   bary_coords_[4*c+lv1] = bp13;
                    facet_cut_plane_[4*c+lv2] = GEO::NO_INDEX;
                    facet_cut_plane_[4*c+lv3] = GEO::NO_INDEX;
                }
            }
        }

        /* Debug builds: check, with an exact predicate, that no tetrahedron generated by
           this call is inverted. The tetrahedra `[0, PREV_TETS_NB)` were modified in place
           by the loop above, so the whole buffer has to be checked. */
        debug_check_tet_orientations(
            coords_, 0, static_cast<GEO::index_t>(coords_.size())/4, CELL_SCALE
            );

        ++cut_planes_nb_;
        if (cut_planes_nb_ > 32)
            LOG::WARN("Cut planes nb == {} > 32, partitions out of uint32_t!", cut_planes_nb_);
    }
}
